name: "Eufy NVR WebRTC Proxy"
description: "A standalone add-on to expose Eufy NVR WebRTC streams to Home Assistant."
version: "0.0.3"
slug: "eufy_nvr"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - share:rw
options:
  auth_token: ""
  station_sn: ""
schema:
  auth_token: str
  station_sn: str
